# Tensorflow Basics

In [1]:
import os
import numpy as np
import tensorflow as tf
from pprint import pprint
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 

## Create Tensor

In [2]:
tf.zeros((5, 4))

<tf.Tensor: id=2, shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [3]:
tf.random.uniform((5, 4))

<tf.Tensor: id=10, shape=(5, 4), dtype=float32, numpy=
array([[0.6593343 , 0.07230306, 0.48296297, 0.10836852],
       [0.9293139 , 0.21496272, 0.4960618 , 0.01479697],
       [0.54694784, 0.51438296, 0.12393415, 0.7816354 ],
       [0.17489398, 0.15952492, 0.470325  , 0.9854485 ],
       [0.9726702 , 0.40210783, 0.2715323 , 0.51948166]], dtype=float32)>

In [4]:
a = tf.random.uniform((5, 4))
print(a)
print(a.shape)
print(type(a))

tf.Tensor(
[[0.4490955  0.9569212  0.18194318 0.5841236 ]
 [0.04345095 0.35750306 0.16177559 0.00886834]
 [0.6274855  0.8926736  0.14408624 0.540465  ]
 [0.69044685 0.28571033 0.4133078  0.38084173]
 [0.5025464  0.46844625 0.9863994  0.11561799]], shape=(5, 4), dtype=float32)
(5, 4)
<class 'tensorflow.python.framework.ops.EagerTensor'>


## Converting between numpy arrary and Tensor

In [5]:
b = a.numpy()
print(b)
print(type(b))

[[0.4490955  0.9569212  0.18194318 0.5841236 ]
 [0.04345095 0.35750306 0.16177559 0.00886834]
 [0.6274855  0.8926736  0.14408624 0.540465  ]
 [0.69044685 0.28571033 0.4133078  0.38084173]
 [0.5025464  0.46844625 0.9863994  0.11561799]]
<class 'numpy.ndarray'>


In [6]:
c = tf.convert_to_tensor(b)
print(c)
print(type(c))

tf.Tensor(
[[0.4490955  0.9569212  0.18194318 0.5841236 ]
 [0.04345095 0.35750306 0.16177559 0.00886834]
 [0.6274855  0.8926736  0.14408624 0.540465  ]
 [0.69044685 0.28571033 0.4133078  0.38084173]
 [0.5025464  0.46844625 0.9863994  0.11561799]], shape=(5, 4), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


## Moving Tensors between devices

In [7]:
a.cpu()

<tf.Tensor: id=23, shape=(5, 4), dtype=float32, numpy=
array([[0.4490955 , 0.9569212 , 0.18194318, 0.5841236 ],
       [0.04345095, 0.35750306, 0.16177559, 0.00886834],
       [0.6274855 , 0.8926736 , 0.14408624, 0.540465  ],
       [0.69044685, 0.28571033, 0.4133078 , 0.38084173],
       [0.5025464 , 0.46844625, 0.9863994 , 0.11561799]], dtype=float32)>

In [8]:
# a.gpu()

## Basic operations

In [9]:
a + b

<tf.Tensor: id=26, shape=(5, 4), dtype=float32, numpy=
array([[0.898191  , 1.9138424 , 0.36388636, 1.1682472 ],
       [0.0869019 , 0.7150061 , 0.32355118, 0.01773667],
       [1.254971  , 1.7853472 , 0.28817248, 1.08093   ],
       [1.3808937 , 0.57142067, 0.8266156 , 0.76168346],
       [1.0050929 , 0.9368925 , 1.9727988 , 0.23123598]], dtype=float32)>

In [10]:
a * b

<tf.Tensor: id=29, shape=(5, 4), dtype=float32, numpy=
array([[2.0168675e-01, 9.1569823e-01, 3.3103321e-02, 3.4120038e-01],
       [1.8879852e-03, 1.2780844e-01, 2.6171342e-02, 7.8647397e-05],
       [3.9373806e-01, 7.9686618e-01, 2.0760845e-02, 2.9210243e-01],
       [4.7671685e-01, 8.1630394e-02, 1.7082332e-01, 1.4504042e-01],
       [2.5255293e-01, 2.1944189e-01, 9.7298378e-01, 1.3367520e-02]],
      dtype=float32)>

## Autograd

In [11]:
a = tf.convert_to_tensor([4], dtype='float32')
b = tf.convert_to_tensor([5], dtype='float32')

with tf.GradientTape() as tape:
    tape.watch([a, b])
    c = tf.pow(a, 2) + 3 * b
pprint(tape.gradient(c, [a, b]))

W0711 12:05:18.801529 140398161102592 deprecation.py:323] From /home/ren/anaconda3/envs/tf2beta/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:1205: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


[<tf.Tensor: id=51, shape=(1,), dtype=float32, numpy=array([8.], dtype=float32)>,
 <tf.Tensor: id=74, shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>]


## Module

In [12]:
class LinearRegression(tf.Module):
    def __init__(self, use_bias=True):
        self.use_bias = use_bias
        
    def build(self, num_features):
        self.weights = tf.random.uniform((num_features,), dtype='float32')
        self.bias = tf.random.uniform((1, ), dtype='float32') if self.use_bias else None
        
    def __call__(self, x):
        out = tf.tensordot(self.weights, x, 1)
        if self.bias:
            out += self.bias
        return out        

In [13]:
lr = LinearRegression(True)
lr.build(num_features=5)
print(lr.weights)
print(lr.bias)

tf.Tensor([0.90094244 0.83180535 0.8709961  0.9859475  0.04009664], shape=(5,), dtype=float32)
tf.Tensor([0.72132206], shape=(1,), dtype=float32)


In [14]:
x = tf.random.uniform((5, 5))
y = tf.random.uniform((4, 1))
print(x, y)

tf.Tensor(
[[0.10816109 0.7041141  0.02964878 0.6321254  0.38572407]
 [0.9581622  0.44130647 0.06271327 0.9114268  0.9963082 ]
 [0.46421063 0.0237124  0.8157301  0.1601386  0.39973223]
 [0.00619853 0.08321834 0.9909061  0.16099322 0.57616127]
 [0.27389348 0.6962029  0.5150317  0.3789699  0.01299489]], shape=(5, 5), dtype=float32) tf.Tensor(
[[0.13241017]
 [0.44373763]
 [0.8123131 ]
 [0.84170616]], shape=(4, 1), dtype=float32)


In [15]:
with tf.GradientTape() as tape:
    tape.watch([lr.weights, lr.bias])
    out = lr(x)
    mse = tf.reduce_mean((y - out)**2)

In [16]:
print(mse)

tf.Tensor(3.289758, shape=(), dtype=float32)


In [17]:
pprint(tape.gradient(mse, [lr.weights, lr.bias]))

[<tf.Tensor: id=185, shape=(5,), dtype=float32, numpy=
array([1.256669 , 2.4021463, 1.4000175, 1.4563565, 1.2101825],
      dtype=float32)>,
 <tf.Tensor: id=178, shape=(1,), dtype=float32, numpy=array([3.515156], dtype=float32)>]
